### ISSUE TITLE
Scaffolding DbContext Not working

### ISSUE THREAD

**Issue by JKAngular** [AnkitSharma-007/BookCart#10]
Scaffolding DbContext Not working

A connection was successfully established with the server, but then an error occurred during the login process. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.)

also can you share table script with Data

**Comment by AnkitSharma-007** [comment]
The code and scaffolding are working fine. Please check if your SQL Server instance is correct or not. Also, verify the connection string.

Sharing data is not possible. Please add your own data to the table.

**Comment by JKAngular** [comment]
Every thing correct. But not working

Share your email I'd I ll send snapshot.

I want know that source code with data shopping cart. Can you help me

I follow your article directly create table some issue come

**Comment by JKAngular** [comment]
Hi
Ankit 

I am also try scafffolding Dbcontext  some issue facing

I m also execute the script directly in sql server some issue I am facing 

snapshot here

can you share your email id

share the dbscript 

Register also not working 


![image](https://user-images.githubusercontent.com/59573064/142961376-0bb5335a-af47-4533-a0c0-fa61b8bfb27e.png)


![image](https://user-images.githubusercontent.com/59573064/142961425-e6533ebd-a859-4833-a7ed-78864895b676.png)


![image](https://user-images.githubusercontent.com/59573064/142961438-9e9943df-c8f9-4514-a339-a304957b28b8.png)

**Comment by JKAngular** [comment]
Hi Ankit

Register Page also not working . can you share the information step by step. can you update working copy



![image](https://user-images.githubusercontent.com/59573064/142969208-97cff77f-6ebb-44a2-98fa-05f2140a84aa.png)


![image](https://user-images.githubusercontent.com/59573064/142969252-8c9b4d47-1f00-46dc-afec-c2706a28c532.png)

**Comment by JKAngular** [comment]
Hi 
Ankit

your project not working properly


![image](https://user-images.githubusercontent.com/59573064/143223682-7addc721-a33e-4f1e-8990-e616cb2da69d.png)

**Comment by JKAngular** [comment]
Hi
Ankit

can you update running code without error in git hub

**Comment by AnkitSharma-007** [comment]
The source code has been updated to .NET 6.0. It is working perfectly fine. Please rebase and run again.

**Comment by JKAngular** [comment]
hi

Ankit sharma

Give me proper solution after can you close it

without solution you closed my comment
