### ISSUE TITLE
can you resolve this registration issue your project  . Update running code.

### ISSUE THREAD

**Issue by JKAngular** [AnkitSharma-007/BookCart#13]
Hi
Ankit

When I register your application it is not working . can you update this then only useful for all people.

can you update running code without error in git hub

![image](https://user-images.githubusercontent.com/59573064/143224945-e73f1c17-dd20-4d62-b774-1cfa96766faf.png)

![image](https://user-images.githubusercontent.com/59573064/143225018-70fd6636-fc8b-43f6-bb78-61d8e656d80f.png)

![image](https://user-images.githubusercontent.com/59573064/143225050-3d28decd-d408-4ec8-a7ee-3d2e49e292c6.png)

**Comment by AnkitSharma-007** [comment]
The source code has been updated to .NET 6. It is working perfectly fine. Please fetch the latest and run the code again. Make sure you follow https://github.com/AnkitSharma-007/BookCart#steps-to-run-the-app
