### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by JamieSlome** [AnkitSharma-007/BookCart#18]
Hey there!

I belong to an open source security research community, and a member (@ibarrionuevo) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by AnkitSharma-007** [comment]
This is my personal project to learn and share knowledge. I am not sure how adding the `SECURITY.md` file will provide any benefits to it. Also, I am not comfortable sharing my email id in public.

**Comment by acciobugs** [comment]
We could help you to improve your project through security findings and fixes :)

**Comment by JamieSlome** [comment]
@AnkitSharma-007 - not to worry, if you would prefer, you can view the report directly here:

https://huntr.dev/bounties/d5ca47a7-0e9e-4910-bf27-298e88c6013a/
