### ISSUE TITLE
How does a reader open a book they've purchased?

### ISSUE THREAD

**Issue by viztastic** [AnkitSharma-007/BookCart#32]
Hi, thanks for the project!

I'm wondering whether it's worth exploring integration with something like KavitaReader for a user to make a purchase and then be able to read their purchased eBooks using something like KavitaReader. Kavita seems pretty full featured and might "just" need an integration to handle permissions for what a user can/can't read based on the eCommerce system.

What do you think?

**Comment by AnkitSharma-007** [comment]
This is a dummy app created for learning and exploring the associated programming concepts.

The user is not actually buying any book coz it is just a simulation. There is no book delivered to the user.

Adding any e-book reader is not required here.
