### ISSUE TITLE
No relation between domain models

### ISSUE THREAD

**Issue by TheTechy1010** [AnkitSharma-007/BookCart#7]
I saw the .NET API project and the DB Script with the Model classes. I am a newbie. is it good to not maintain any relation between models? I am asking because your app is working awesome though you have violated some principles of OOP and RDBMS. Should we focus on both the things or just code to get the work done. I liked that domain classes are  clean and proper clean coding is followed by you.

**Comment by AnkitSharma-007** [comment]
I am not sure what do you mean by "relation b/w models". Do you want to have one class being referenced in another? Also can you plz let me know what principles of OOP you think are violated here? 

I believe having a good project architecture is more important than just getting the work done.

**Comment by TheTechy1010** [comment]
I mean there is no relations defined between the models (or tables)(No foreign key) in the database which is i think not a good practice while designing a RDBMS system. Don't get me wrong it is only my opinion. As a new learner i get confused when i see a new pattern of code. Also the models used in the system has no Aggregation ,or composition or Association. It definitely gets the work done but tell me how you think while designing the system. Please let me know. It will help me better understanding the development process.

**Comment by AnkitSharma-007** [comment]
Personally, I am not a fan of foreign key (FK). In this DB, e.g. you can refer bookid as FK in other tables but I don't think it will have any impact. Why to make things complex unnecessarily?

My DB design is very simple. I use DB just to store data not for any data processing or other logic. I put complexities at the API level where I can manipulate data using the code as I like. 

While designing the project my aim was to keep things simple and easy to understand. Use principles and standard practices to make your work easy. Do not overdo them and make the things complex.

I could have used Aggregation with the book and categories class, but I did not. And I now I don't remember why 🙂

**Comment by TheTechy1010** [comment]
Fair enough. I like your opinion that you keep things simple. For a freshman like me..these are confusing areas. I am building projects for my resume so I would like to take guidance from you if you are willing to help in future in regards of .NET and Angular. How can i contact you btw?? I liked your coding style. Thanks for responding.

**Comment by AnkitSharma-007** [comment]
You can contact me here - https://ankitsharmablogs.com/contact/

Share your problem and let me see what I can do. Please note that any help for your personal projects will be a charged service.

**Comment by TheTechy1010** [comment]
Ya sure..Thanks
